### ISSUE TITLE
Move NWBib vocabs to NWBib repo

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-vocabs#101]
You probably already addressed this, @fsteeg. With the vocabs' canonical URI now being `https://nwbib.de/...we should probably move it over to the NWBib repo. What do you think?

**Comment by acka47** [comment]
As discussed offline, we will move the skos files to /conf in the nwbib repo and add an additional skos file for the broader relations that are missing in Wikidata (see https://github.com/hbz/nwbib/issues/489) that can then also be used for other configurations that might come.

**Comment by acka47** [comment]
I added the basic config file for hierarchies with https://github.com/hbz/nwbib/commit/11eb6218c1206b7dfae9cb4404ea67889839d4bf. For this, I copied the whole information for each entry from the existing nwbib-spatial.ttl. However, as some entries (those with nwbib-spatial:QID) are – except for the broader information are generated from Wikidata, we might substract some triples.

**Comment by fsteeg** [comment]
Commented in https://github.com/hbz/nwbib/pull/493#issuecomment-543730466.

**Comment by fsteeg** [comment]
For the record: we've actually done something different than the title here: we've set up a base nwbib-spatial SKOS file in the nwbib repo, which we use there to create the full classification by using Wikidata. The resulting file is not checked into the nwbib repo, but instead still versioned here. The productive nwbib app also uses the static file here. I think this is a good setup for now, since we will be working in that area in the context of managing updates in Wikidata / keeping our own buffer. (Do we have a ticket for that?).

**Comment by acka47** [comment]
> Do we have a ticket for that?

Not yet. But I think it is ok to wait with opening one until we want to trigger the first update.
