### ISSUE TITLE
Neue Codes für Bibliothekstypen gemäß dem Sigelverzeichnis

### ISSUE THREAD

**Issue by TobiasNx** [hbz/lobid-vocabs#176]
Mail from @cKlee :

> 
> wir haben zwei neue Codes
> 83 -> Gedenkstätte
> 85 -> Sammlung
> Ich habe die Doku angepasst.

Wir sollten diese Werte in http://purl.org/lobid/libtype#scheme übernehmen. -> [Dokumentation](https://sigel.staatsbibliothek-berlin.de/vergabe/adressenformat/805)

**Comment by acka47** [comment]
I found out, why the English label for `n86` wasn't shown although the concept has been part of the SKOS vocab for a long time: capitalized RDF property names, see https://github.com/hbz/lobid-vocabs/pull/215/commits/5d0352f4cf16b1f3ba2ae3d91d6e0529be6806ea

**Comment by TobiasNx** [comment]
Sammlung and our type: Collection could create a conflict

**Comment by acka47** [comment]
> Sammlung and our type: Collection could create a conflict

This can indeed get confusing as they refer to different kinds of things: e-resources collection (`bibo:Collection`) vs. physical collection (`http://purl.org/lobid/libtype#n85`). However, as one is put under `type` and the other under `classification` we at least have them separated well in the data model so that there will be no technical conflict.
