### ISSUE TITLE
Add new top-level concepts

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-vocabs#72]
See https://github.com/hbz/nwbib/issues/397#issue-263449101. 

- [x] Add the following concepts without notations:
> Nordrhein-Westfalen insgesamt. Landesteile
Landschaften in Nordrhein-Westfalen
Kirchliche Gebiete in Nordrhein-Westfalen
Historische Territorien und Gebiete
Regierungsbezirke, Kreise, Orte. Euregio
- [x] make them top-level concepts instead of those that currently are (`skos:hasTopConcept`)
- [x] add `skos:broader`/`skos:narrower` relations

**Comment by fsteeg** [comment]
Same for nwbib.ttl, see https://github.com/hbz/nwbib/issues/396:

- [ ] Add the following concepts with notations:
> 1 Landeskunde (allgemein. Geo-u. Biowissenschaften)
2 Landeskunde (historisch)
4 Staat. Politik. Verwaltung. Recht
5 Bevölkerung. Soziales. Wirtschaft. Raumordnung. Umweltschutz
6 Religion
7 Volkskunde. Gesellschaft. Kultur. Bildung
8 Künste. Medien
- [ ] make them top-level concepts instead of those that currently are
- [ ] add `skos:broader`/`skos:narrower` relations

**Comment by acka47** [comment]
+1
